version: '2'

services:
  firefox:
    container_name: 'firefox'
    image: 'selenium/standalone-firefox:88.0'
  scraper:
    container_name: 'scraper'
    image: 'stock-scrapers/boursorama-france:0.2'
    volumes:
        - './mnt:/app/mnt'
    depends_on:
      - firefox